services:
  chronoframe:
    image: kenv1e/chronoframe-private:latest
    container_name: chronoframe
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data

